package models

import (
	utils "agrisa_utils"
	"time"

	"github.com/google/uuid"
)

// ============================================================================
// CLAIMS & PAYOUTS
// ============================================================================

type Claim struct {
	ID                     uuid.UUID     `json:"id" db:"id"`
	ClaimNumber            string        `json:"claim_number" db:"claim_number"`
	RegisteredPolicyID     uuid.UUID     `json:"registered_policy_id" db:"registered_policy_id"`
	BasePolicyID           uuid.UUID     `json:"base_policy_id" db:"base_policy_id"`
	FarmID                 uuid.UUID     `json:"farm_id" db:"farm_id"`
	BasePolicyTriggerID    uuid.UUID     `json:"base_policy_trigger_id" db:"base_policy_trigger_id"`
	TriggerTimestamp       int64         `json:"trigger_timestamp" db:"trigger_timestamp"`
	ClaimAmount            float64       `json:"claim_amount" db:"claim_amount"`
	Status                 ClaimStatus   `json:"status" db:"status"`
	AutoGenerated          bool          `json:"auto_generated" db:"auto_generated"`
	PartnerReviewTimestamp *int64        `json:"partner_review_timestamp,omitempty" db:"partner_review_timestamp"`
	PartnerDecision        *string       `json:"partner_decision,omitempty" db:"partner_decision"`
	PartnerNotes           *string       `json:"partner_notes,omitempty" db:"partner_notes"`
	ReviewedBy             *string       `json:"reviewed_by,omitempty" db:"reviewed_by"`
	AutoApprovalDeadline   *int64        `json:"auto_approval_deadline,omitempty" db:"auto_approval_deadline"`
	AutoApproved           bool          `json:"auto_approved" db:"auto_approved"`
	EvidenceSummary        utils.JSONMap `json:"evidence_summary,omitempty" db:"evidence_summary"` // JSONB
	CreatedAt              time.Time     `json:"created_at" db:"created_at"`
	UpdatedAt              time.Time     `json:"updated_at" db:"updated_at"`
}

type Payout struct {
	ID                          uuid.UUID    `json:"id" db:"id"`
	ClaimID                     uuid.UUID    `json:"claim_id" db:"claim_id"`
	RegisteredPolicyID          uuid.UUID    `json:"registered_policy_id" db:"registered_policy_id"`
	FarmID                      uuid.UUID    `json:"farm_id" db:"farm_id"`
	FarmerID                    string       `json:"farmer_id" db:"farmer_id"`
	PayoutAmount                float64      `json:"payout_amount" db:"payout_amount"`
	Currency                    string       `json:"currency" db:"currency"`
	Status                      PayoutStatus `json:"status" db:"status"`
	InitiatedAt                 *int64       `json:"initiated_at,omitempty" db:"initiated_at"`
	CompletedAt                 *int64       `json:"completed_at,omitempty" db:"completed_at"`
	FarmerConfirmed             bool         `json:"farmer_confirmed" db:"farmer_confirmed"`
	FarmerConfirmationTimestamp *int64       `json:"farmer_confirmation_timestamp,omitempty" db:"farmer_confirmation_timestamp"`
	FarmerRating                *int         `json:"farmer_rating,omitempty" db:"farmer_rating"`
	FarmerFeedback              *string      `json:"farmer_feedback,omitempty" db:"farmer_feedback"`
	CreatedAt                   time.Time    `json:"created_at" db:"created_at"`
}
